const String garlicDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String lettuceDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String carrotDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String eggDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String serranoChiliDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String tomatoesDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String avocadoDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String sunFlowerDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades.\\n\\nEsta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades.\\n\\nPor ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';

const String strawberryDescription =
    '{"Beneficios":"Las semillas de girasol se caracterizan por ser ricas en vitamina E, lo que les confiere diversas propiedades. Esta vitamina es un potente antioxidante, lo que ayuda a mantener sanas las células y con ello evitar diversas enfermedades. Por ejemplo, evitan que se oxide el colesterol, impidiendo así que se adhiera a las paredes de los vasos sanguíneos, reduciendo el riesgo de eventos cardiovasculares.","Sabias que":"También se les llama maíz de teja, debido a que los habitantes del pequeño poblado de Pinal de Amoles en Querétaro, donde el atole de esa semilla es tradicional, dejaban secar sobre las tejas de sus casas.","¿Las semillas de girasol engordan?":"Todo depende de cuánto comas. Ciertamente no son bajas en calorías. 100 gramos de semillas de girasol proporcionan 584 kcal. Veamos en detalle los valores nutricionales de las semillas de girasol."}';
